from django.urls import path
from .views import (
    add_to_cart,
    email_exists,
    empty_cart,
    get_cart_user,
    get_category,
    get_comments,
    get_size_details,
    get_subcateregory_by_category,
    get_user,
    get_variant_details,
    hello_world,
    get_products,
    get_product,
    get_product_by_category,
    get_product_by_subcategory,
    get_categories,
    login,
    logout,
    register,
    remove_from_cart,
    save_comment,
    update_cart,
    username_exists,
)

urlpatterns = [
    path("hello/", hello_world),
    path("products/", get_products, name="get_products"),
    path("categories/", get_categories, name="get_categories"),
    path("products/<int:pk>/", get_product, name="get_product"),
    path(
        "products/category/<int:category_id>/",
        get_product_by_category,
        name="get_product_by_category",
    ),
    path(
        "products/subcategory/<int:subcategory_id>/",
        get_product_by_subcategory,
        name="get_product_by_subcategory",
    ),
    path(
        "categories/<int:category_id>/subcategories/",
        get_subcateregory_by_category,
        name="get_subcateregory_by_category",
    ),
    path(
        "products/variant/<int:variant_id>/",
        get_variant_details,
        name="get_variant_details",
    ),
    path("products/size/<int:size_id>/", get_size_details, name="get_size_details"),
    path("categories/<int:pk>/", get_category, name="get_category"),
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
    path("register/", register, name="register"),
    path("user/username/", username_exists, name="username_exists"),
    path("user/email/", email_exists, name="email_exists"),
    path("comments/save/", save_comment, name="save_comment"),
    path("comments/<int:product_id>/", get_comments, name="get_comments"),
    path("user/<int:user_id>/", get_user, name="get_user"),
    path("cart/<int:user_id>/", get_cart_user, name="get_cart_user"),
    path("cart/add/", add_to_cart, name="add_to_cart"),
    path("cart/update/", update_cart, name="update_cart"),
    path("cart/<int:user_id>/empty/", empty_cart, name="empty_cart"),
    path("cart/remove/", remove_from_cart, name="remove_from_cart"),
]
