from django.urls import path
from .views import (
    ActivateAccountView,
    RegisterView,
    add_to_cart,
    already_in_wishlist,
    email_exists,
    empty_cart,
    get_cart_user,
    get_category,
    get_comments,
    get_size_details,
    get_subcateregory_by_category,
    get_user,
    get_variant_details,
    hello_world,
    get_products,
    get_product,
    get_product_by_category,
    get_product_by_subcategory,
    get_categories,
    login,
    logout,
    remove_from_cart,
    save_comment,
    send_verification_code,
    reset_password,
    update_cart,
    username_exists,
    add_to_wishlist,
    get_wishlist,
    remove_from_wishlist,
    empty_wishlist,
    user_me,
)

urlpatterns = [
    path("hello/", hello_world),
    path("products/", get_products, name="get_products"),
    path("categories/", get_categories, name="get_categories"),
    path("products/<int:pk>/", get_product, name="get_product"),
    path(
        "products/category/<int:category_id>/",
        get_product_by_category,
        name="get_product_by_category",
    ),
    path(
        "products/subcategory/<int:subcategory_id>/",
        get_product_by_subcategory,
        name="get_product_by_subcategory",
    ),
    path(
        "categories/<int:category_id>/subcategories/",
        get_subcateregory_by_category,
        name="get_subcateregory_by_category",
    ),
    path(
        "products/variant/<int:variant_id>/",
        get_variant_details,
        name="get_variant_details",
    ),
    path("products/size/<int:size_id>/", get_size_details, name="get_size_details"),
    path("categories/<int:pk>/", get_category, name="get_category"),
    # Authentication endpoints
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path(
        "activate/<uuid:email_verification_token>/",
        ActivateAccountView.as_view(),
        name="activate_account",
    ),  # <-- Ajouté pour l'activation
    # User-related endpoints
    path("user/me/", user_me, name="get_current_user"),
    path("user/username/", username_exists, name="username_exists"),
    path("user/email/", email_exists, name="email_exists"),
    path(
        "user/send_verification_code/",
        send_verification_code,
        name="send_verification_code",
    ),
    path("user/reset_password/", reset_password, name="reset_password"),
    path("comments/save/", save_comment, name="save_comment"),
    path("comments/<int:product_id>/", get_comments, name="get_comments"),
    path("user/<int:user_id>/", get_user, name="get_user"),
    path("cart/", get_cart_user, name="get_cart_user"),
    path("cart/add/", add_to_cart, name="add_to_cart"),
    path("cart/update/", update_cart, name="update_cart"),
    path("cart/empty/", empty_cart, name="empty_cart"),
    path("cart/remove/", remove_from_cart, name="remove_from_cart"),
    path("wishlist/", get_wishlist, name="user_wishlist"),
    path("wishlist/add/", add_to_wishlist, name="add_to_wishlist"),
    path("wishlist/remove/", remove_from_wishlist, name="remove_from_wishlist"),
    path("wishlist/empty/", empty_wishlist, name="empty_wishlist"),
    path("wishlist/already_exists/", already_in_wishlist, name="already_in_wishlist"),
]
